<?php
/*
 * Generated from the Advanced Custom Fields Plugin
 */

 if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_59528eae94a6c',
	'title' => 'Actuators Specifications',
	'fields' => array (
		array (
			'key' => 'field_59528ecd269f2',
			'label' => 'Weight',
			'name' => 'actu_weight',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'lbs.',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array (
			'key' => 'field_59528ef072337',
			'label' => 'Max Pressure',
			'name' => 'actu_max_pressure',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array (
			'key' => 'field_59528f1172338',
			'label' => 'Actuator Type',
			'name' => 'actu_type',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Hydraulic' => 'Hydraulic',
				'Pneumatic' => 'Pneumatic',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_59528f5972339',
			'label' => 'Fluid Displacement',
			'name' => 'actu_fluid_displacement',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'2.36' => '2.36',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 1,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array (
			'key' => 'field_59528f7d7233a',
			'label' => 'Fluid Type',
			'name' => 'actu_fluid_type',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'brake fluid' => 'brake fluid',
				'hydraulic oil' => 'hydraulic oil',
				'mineral oil' => 'mineral oil',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 1,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array (
			'key' => 'field_59529057893d3',
			'label' => 'Typical Specifications',
			'name' => 'actu_typical_specifications',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Tables copied from an Excel spreadsheet will be formatted correctly for this field and can therefore be pasted in directly when using the "Paste as Text" tool.',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'product',
			),
			array (
				'param' => 'post_taxonomy',
				'operator' => '==',
				'value' => 'product_cat:actuators',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59430a94b4b63',
	'title' => 'Common Product Fields',
	'fields' => array (
		array (
			'key' => 'field_59430ab245f32',
			'label' => 'Introduction',
			'name' => 'introduction',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59430ac26647b',
			'label' => 'Spec Sheet',
			'name' => 'spec_sheet',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_594431101be23',
			'label' => 'Torque Information',
			'name' => 'torque_information',
			'type' => 'image',
			'instructions' => 'Upload an image of the torque information graph',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_59ef5517735dd',
			'label' => 'Torque Information 2',
			'name' => 'torque_information_2',
			'type' => 'image',
			'instructions' => 'Upload an image of the torque information graph',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_5945bd6db3ef5',
			'label' => 'Reference Dimensions 1',
			'name' => 'reference_dimensions_1',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_5945bd7fb3ef6',
			'label' => 'Reference Dimensions 2',
			'name' => 'reference_dimensions_2',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_5945bd86b3ef7',
			'label' => 'Reference Dimensions 3',
			'name' => 'reference_dimensions_3',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'product',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5988a2cd3f047',
	'title' => 'Homepage Icons',
	'fields' => array (
		array (
			'key' => 'field_5988a2da90350',
			'label' => 'Homepage Icons',
			'name' => 'homepage_icons',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_5988a2ef90351',
					'label' => 'Title',
					'name' => 'title',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5988a2f790352',
					'label' => 'Icon',
					'name' => 'icon',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_5988a505d03d2',
					'label' => 'Link',
					'name' => 'link',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'page',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'allow_archives' => 1,
					'multiple' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page',
				'operator' => '==',
				'value' => '5',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5942b5ebd77a1',
	'title' => 'Hydraulic and Mechanical Specifications',
	'fields' => array (
		array (
			'key' => 'field_5942b6f57d2b6',
			'label' => 'Weight',
			'name' => 'hydraulic_weight',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'lbs.',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array (
			'key' => 'field_5942b8087d2bb',
			'label' => 'Rotor diameter',
			'name' => 'hydraulic_rotor_diameter',
			'type' => 'text',
			'instructions' => 'Input rotor diameter range in inches',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5942b88abfff8',
			'label' => 'Rotor thickness',
			'name' => 'hydraulic_rotor_thickness',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5942b897bfff9',
			'label' => 'Lining type',
			'name' => 'hydraulic_lining_type',
			'type' => 'select',
			'instructions' => 'Select all that apply',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Semi-Metallic' => 'Semi-Metallic',
				'Sintered' => 'Sintered',
				'Non-Asbestos Organic' => 'Non-Asbestos Organic',
				'Ceramic' => 'Ceramic',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 1,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array (
			'key' => 'field_5942b902bfffa',
			'label' => 'Total lining area',
			'name' => 'hydraulic_total_lining_area',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'sq. in.',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array (
			'key' => 'field_5942b923bfffb',
			'label' => 'Usable lining thickness per pad',
			'name' => 'hydraulic_usable_lining_thickness',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'in.',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array (
			'key' => 'field_5942b936bfffc',
			'label' => 'Offset',
			'name' => 'hydraulic_offset',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array (
			'key' => 'field_5942ba30ffdcb',
			'label' => 'Piston diameter',
			'name' => 'hydraulic_piston_diameter',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_5942bd3e28536',
			'label' => 'Max pressure',
			'name' => 'hydraulic_max_pressure',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'psi',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array (
			'key' => 'field_5942beb9d6105',
			'label' => 'Fluid displacement',
			'name' => 'hydraulic_fluid_displacement',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5942bed4d6106',
			'label' => 'Fluid type',
			'name' => 'hydraulic_fluid_type',
			'type' => 'select',
			'instructions' => 'Select all that apply',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'brake fluid' => 'brake fluid',
				'hydraulic oil' => 'hydraulic oil',
				'mineral oil' => 'mineral oil',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 1,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array (
			'key' => 'field_5942befed6107',
			'label' => 'Fluid inlet',
			'name' => 'hydraulic_fluid_inlet',
			'type' => 'select',
			'instructions' => 'Select all that apply',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'N/A' => 'N/A',
				0 => '0',
				'12:00' => '12:00',
				'1:00' => '1:00',
				'2:00' => '2:00',
				'3:00' => '3:00',
				'4:00' => '4:00',
				'5:00' => '5:00',
				'6:00' => '6:00',
				'7:00' => '7:00',
				'8:00' => '8:00',
				'9:00' => '9:00',
				'10:00' => '10:00',
				'11:00' => '11:00',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 1,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array (
			'key' => 'field_5942bf72d6108',
			'label' => 'Bleeder',
			'name' => 'hydraulic_bleeder',
			'type' => 'select',
			'instructions' => 'Select all that apply',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'N/A' => 'N/A',
				0 => '0',
				'12:00' => '12:00',
				'1:00' => '1:00',
				'2:00' => '2:00',
				'3:00' => '3:00',
				'4:00' => '4:00',
				'5:00' => '5:00',
				'6:00' => '6:00',
				'7:00' => '7:00',
				'8:00' => '8:00',
				'9:00' => '9:00',
				'10:00' => '10:00',
				'11:00' => '11:00',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 1,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array (
			'key' => 'field_595291ecfb534',
			'label' => 'Clamp Load',
			'name' => 'clamp_load',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'lbs.',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array (
			'key' => 'field_5952920efb535',
			'label' => 'Maximum Lever Force',
			'name' => 'maximum_lever_force',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'product',
			),
			array (
				'param' => 'post_taxonomy',
				'operator' => '==',
				'value' => 'product_cat:hydraulic-brakes-type',
			),
		),
		array (
			array (
				'param' => 'post_taxonomy',
				'operator' => '==',
				'value' => 'product_cat:mechanical-brakes',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5988cccee5da9',
	'title' => 'Markets Columns',
	'fields' => array (
		array (
			'key' => 'field_5988ccda1d825',
			'label' => 'Col 1',
			'name' => 'col_1',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array (
			'key' => 'field_5988cce41d826',
			'label' => 'Col 2',
			'name' => 'col_2',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array (
			'key' => 'field_5988cceb1d827',
			'label' => 'Col 3',
			'name' => 'col_3',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-markets.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59512fd0c82a8',
	'title' => 'Master Cylinder Specifications',
	'fields' => array (
		array (
			'key' => 'field_59512ffb97e47',
			'label' => 'Weight',
			'name' => 'master_cyl_weight',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'lbs.',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array (
			'key' => 'field_5951308f082b4',
			'label' => 'Piston Diameter',
			'name' => 'master_cyl_piston_diameter',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_595130e6082b5',
			'label' => 'Lever Ration',
			'name' => 'master_cyl_lever_ration',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'4.5:1' => '4.5:1',
				'3.3:1' => '3.3:1',
				'4.8:1' => '4.8:1',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 1,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array (
			'key' => 'field_5951314c082b6',
			'label' => 'Hand',
			'name' => 'master_cyl_hand',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'left' => 'left',
				'right' => 'right',
				'both' => 'both',
			),
			'default_value' => array (
			),
			'allow_null' => 1,
			'multiple' => 1,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array (
			'key' => 'field_595132093c5f0',
			'label' => 'Brake light switch available:',
			'name' => 'master_cyl_brake_light',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Yes' => 'Yes',
				'No' => 'No',
				'Unknown' => 'Unknown',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array (
			'key' => 'field_5951323a67d6a',
			'label' => 'Fluid Type',
			'name' => 'master_cyl_fluid_type',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'brake fluid' => 'brake fluid',
				'hydraulic oil' => 'hydraulic oil',
				'mineral oil' => 'mineral oil',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'product',
			),
			array (
				'param' => 'post_taxonomy',
				'operator' => '==',
				'value' => 'product_cat:master-cylinder',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59430a1f13ee6',
	'title' => 'Additional Specifications',
	'fields' => array (
		array (
			'key' => 'field_59430a2912946',
			'label' => 'Additional Specifications',
			'name' => 'additional_specifications',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_59430a4012947',
					'label' => 'Specification Label',
					'name' => 'specification_label',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59430a4b12948',
					'label' => 'Specification Value',
					'name' => 'specification_value',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'product',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;

?>
